export type SurfSpot = {
  slug: string;
  name: string;
  region: string;
  country: string;
  lat: number;
  lon: number;
  defaultRadiusMiles: number;
  tags?: string[];
  aliases?: string[];
};

export const surfSpots: SurfSpot[] = [
  {
    slug: "huntington-beach-pier",
    name: "Huntington Beach Pier",
    region: "California",
    country: "United States",
    lat: 33.6543,
    lon: -118.003,
    defaultRadiusMiles: 25,
    tags: ["california", "southern-california", "pier"],
    aliases: ["hb pier", "surf city", "huntington beach"],
  },
  {
    slug: "trestles",
    name: "Trestles",
    region: "California",
    country: "United States",
    lat: 33.3847,
    lon: -117.5936,
    defaultRadiusMiles: 25,
    tags: ["california", "san-clemente"],
    aliases: ["lowers", "lower trestles", "san onofre"],
  },
  {
    slug: "malibu-first-point",
    name: "Malibu First Point",
    region: "California",
    country: "United States",
    lat: 34.035,
    lon: -118.6774,
    defaultRadiusMiles: 25,
    tags: ["california", "los-angeles"],
    aliases: ["malibu", "surfrider beach"],
  },
  {
    slug: "pipeline",
    name: "Pipeline",
    region: "Oahu",
    country: "United States",
    lat: 21.6657,
    lon: -158.0521,
    defaultRadiusMiles: 25,
    tags: ["hawaii", "north-shore"],
    aliases: ["banzai pipeline", "ehukai beach"],
  },
  {
    slug: "waimea-bay",
    name: "Waimea Bay",
    region: "Oahu",
    country: "United States",
    lat: 21.6408,
    lon: -158.0643,
    defaultRadiusMiles: 25,
    tags: ["hawaii", "north-shore"],
  },
  {
    slug: "mavericks",
    name: "Mavericks",
    region: "California",
    country: "United States",
    lat: 37.4942,
    lon: -122.5,
    defaultRadiusMiles: 35,
    tags: ["california", "half-moon-bay", "big-wave"],
  },
  {
    slug: "steamer-lane",
    name: "Steamer Lane",
    region: "California",
    country: "United States",
    lat: 36.9516,
    lon: -122.0263,
    defaultRadiusMiles: 25,
    tags: ["california", "santa-cruz"],
  },
  {
    slug: "pleasure-point",
    name: "Pleasure Point",
    region: "California",
    country: "United States",
    lat: 36.9563,
    lon: -121.9696,
    defaultRadiusMiles: 25,
    tags: ["california", "santa-cruz"],
  },
  {
    slug: "ocean-beach-san-francisco",
    name: "Ocean Beach",
    region: "California",
    country: "United States",
    lat: 37.7594,
    lon: -122.5107,
    defaultRadiusMiles: 35,
    tags: ["california", "san-francisco"],
    aliases: ["ocean beach sf", "ob sf"],
  },
  {
    slug: "newport-beach-56th-street",
    name: "Newport Beach 56th Street",
    region: "California",
    country: "United States",
    lat: 33.6313,
    lon: -117.9533,
    defaultRadiusMiles: 25,
    tags: ["california", "orange-county"],
  },
  {
    slug: "blacks-beach",
    name: "Blacks Beach",
    region: "California",
    country: "United States",
    lat: 32.8898,
    lon: -117.2533,
    defaultRadiusMiles: 25,
    tags: ["california", "san-diego"],
  },
  {
    slug: "la-jolla-shores",
    name: "La Jolla Shores",
    region: "California",
    country: "United States",
    lat: 32.857,
    lon: -117.256,
    defaultRadiusMiles: 25,
    tags: ["california", "san-diego"],
  },
  {
    slug: "cocoa-beach-pier",
    name: "Cocoa Beach Pier",
    region: "Florida",
    country: "United States",
    lat: 28.367,
    lon: -80.6023,
    defaultRadiusMiles: 30,
    tags: ["florida", "east-coast"],
  },
  {
    slug: "new-smyrna-beach",
    name: "New Smyrna Beach",
    region: "Florida",
    country: "United States",
    lat: 29.0258,
    lon: -80.9262,
    defaultRadiusMiles: 30,
    tags: ["florida", "east-coast"],
  },
  {
    slug: "sebastian-inlet",
    name: "Sebastian Inlet",
    region: "Florida",
    country: "United States",
    lat: 27.8606,
    lon: -80.4456,
    defaultRadiusMiles: 30,
    tags: ["florida", "east-coast"],
  },
  {
    slug: "wrightsville-beach",
    name: "Wrightsville Beach",
    region: "North Carolina",
    country: "United States",
    lat: 34.2085,
    lon: -77.7964,
    defaultRadiusMiles: 30,
    tags: ["north-carolina", "east-coast"],
  },
  {
    slug: "cape-hatteras-lighthouse",
    name: "Cape Hatteras Lighthouse",
    region: "North Carolina",
    country: "United States",
    lat: 35.2505,
    lon: -75.528,
    defaultRadiusMiles: 35,
    tags: ["north-carolina", "outer-banks"],
  },
  {
    slug: "montauk",
    name: "Montauk",
    region: "New York",
    country: "United States",
    lat: 41.0359,
    lon: -71.9545,
    defaultRadiusMiles: 35,
    tags: ["new-york", "long-island"],
  },
  {
    slug: "rincon-puerto-rico",
    name: "Rincon",
    region: "Puerto Rico",
    country: "United States",
    lat: 18.3402,
    lon: -67.2509,
    defaultRadiusMiles: 30,
    tags: ["puerto-rico", "caribbean"],
  },
  {
    slug: "tofinino-cox-bay",
    name: "Cox Bay",
    region: "British Columbia",
    country: "Canada",
    lat: 49.1012,
    lon: -125.8725,
    defaultRadiusMiles: 35,
    tags: ["canada", "tofino"],
    aliases: ["tofino", "cox bay tofino"],
  },
  {
    slug: "bondi-beach",
    name: "Bondi Beach",
    region: "New South Wales",
    country: "Australia",
    lat: -33.8915,
    lon: 151.2767,
    defaultRadiusMiles: 30,
    tags: ["australia", "sydney"],
  },
  {
    slug: "bells-beach",
    name: "Bells Beach",
    region: "Victoria",
    country: "Australia",
    lat: -38.3692,
    lon: 144.2836,
    defaultRadiusMiles: 30,
    tags: ["australia", "victoria"],
  },
  {
    slug: "snapper-rocks",
    name: "Snapper Rocks",
    region: "Queensland",
    country: "Australia",
    lat: -28.1646,
    lon: 153.5502,
    defaultRadiusMiles: 30,
    tags: ["australia", "gold-coast"],
  },
  {
    slug: "burleigh-heads",
    name: "Burleigh Heads",
    region: "Queensland",
    country: "Australia",
    lat: -28.0918,
    lon: 153.4593,
    defaultRadiusMiles: 30,
    tags: ["australia", "gold-coast"],
  },
  {
    slug: "margaret-river-main-break",
    name: "Margaret River Main Break",
    region: "Western Australia",
    country: "Australia",
    lat: -33.9765,
    lon: 114.9878,
    defaultRadiusMiles: 35,
    tags: ["australia", "western-australia"],
  },
  {
    slug: "raglan-manu-bay",
    name: "Raglan Manu Bay",
    region: "Waikato",
    country: "New Zealand",
    lat: -37.8112,
    lon: 174.8155,
    defaultRadiusMiles: 30,
    tags: ["new-zealand", "raglan"],
    aliases: ["manu bay", "raglan"],
  },
  {
    slug: "jeffreys-bay",
    name: "Jeffreys Bay",
    region: "Eastern Cape",
    country: "South Africa",
    lat: -34.0507,
    lon: 24.921,
    defaultRadiusMiles: 35,
    tags: ["south-africa", "j-bay"],
    aliases: ["j-bay", "supertubes"],
  },
  {
    slug: "dungeons",
    name: "Dungeons",
    region: "Western Cape",
    country: "South Africa",
    lat: -34.0572,
    lon: 18.3336,
    defaultRadiusMiles: 35,
    tags: ["south-africa", "cape-town", "big-wave"],
  },
  {
    slug: "hossegor-la-graviere",
    name: "Hossegor La Graviere",
    region: "Nouvelle-Aquitaine",
    country: "France",
    lat: 43.6655,
    lon: -1.4428,
    defaultRadiusMiles: 30,
    tags: ["france", "hossegor"],
  },
  {
    slug: "mundaka",
    name: "Mundaka",
    region: "Basque Country",
    country: "Spain",
    lat: 43.4074,
    lon: -2.6981,
    defaultRadiusMiles: 30,
    tags: ["spain", "basque-country"],
  },
  {
    slug: "nazare",
    name: "Nazare",
    region: "Leiria",
    country: "Portugal",
    lat: 39.6057,
    lon: -9.0764,
    defaultRadiusMiles: 35,
    tags: ["portugal", "big-wave"],
  },
  {
    slug: "ericeira-ribeira-dilhas",
    name: "Ribeira d'Ilhas",
    region: "Ericeira",
    country: "Portugal",
    lat: 39.0057,
    lon: -9.4202,
    defaultRadiusMiles: 30,
    tags: ["portugal", "ericeira"],
  },
  {
    slug: "uluwatu",
    name: "Uluwatu",
    region: "Bali",
    country: "Indonesia",
    lat: -8.815,
    lon: 115.087,
    defaultRadiusMiles: 30,
    tags: ["indonesia", "bali"],
  },
  {
    slug: "padang-padang",
    name: "Padang Padang",
    region: "Bali",
    country: "Indonesia",
    lat: -8.8106,
    lon: 115.1037,
    defaultRadiusMiles: 30,
    tags: ["indonesia", "bali"],
  },
  {
    slug: "cloudbreak",
    name: "Cloudbreak",
    region: "Mamanuca Islands",
    country: "Fiji",
    lat: -17.8569,
    lon: 177.1824,
    defaultRadiusMiles: 35,
    tags: ["fiji"],
  },
  {
    slug: "teahupoo",
    name: "Teahupoo",
    region: "Tahiti",
    country: "French Polynesia",
    lat: -17.8494,
    lon: -149.2676,
    defaultRadiusMiles: 35,
    tags: ["tahiti", "french-polynesia"],
  },
  {
    slug: "puerto-escondido-zicatela",
    name: "Puerto Escondido Zicatela",
    region: "Oaxaca",
    country: "Mexico",
    lat: 15.8527,
    lon: -97.0516,
    defaultRadiusMiles: 30,
    tags: ["mexico", "oaxaca"],
    aliases: ["zicatela", "puerto escondido"],
  },
  {
    slug: "punta-de-lobos",
    name: "Punta de Lobos",
    region: "O'Higgins",
    country: "Chile",
    lat: -34.4254,
    lon: -72.0496,
    defaultRadiusMiles: 35,
    tags: ["chile", "big-wave"],
  },
];

export function getSurfSpotBySlug(slug: string): SurfSpot | undefined {
  return surfSpots.find((spot) => spot.slug === slug);
}

export function searchSurfSpots(query: string): SurfSpot[] {
  const q = query.trim().toLowerCase();
  if (!q) return surfSpots;

  return surfSpots.filter((spot) => {
    const haystack = [
      spot.name,
      spot.region,
      spot.country,
      spot.slug,
      ...(spot.tags || []),
      ...(spot.aliases || []),
    ]
      .join(" ")
      .toLowerCase();

    return haystack.includes(q);
  });
}
